name: CI

on: [push, pull_request]

env:
  NODE_VERSION: 12.x

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm install
  
  lint:
    runs-on: ubuntu-latest
    needs: [install]
    
    steps:
    - uses: actions/checkout@v2
    - run: npm run lint --if-present
  
  test:
    runs-on: ubuntu-latest
    needs: [install]
    
    steps:
    - uses: actions/checkout@v2
    - run: npm test
    
  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
    - uses: actions/checkout@v2
    - run: npm run build --if-present
