name: CI

on: [push, pull_request]

env:
  NODE_VERSION: 12.x

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint --if-present
    - run: npm test
    - run: npm run build --if-present
